import type { ContentBundle } from "./types";

export const TEST_CONTENT: ContentBundle = {
  items: {
    axe: {
      id: "axe",
      name: "Axe",
      description: "Test axe",
      category: "tool",
      stackable: false,
      maxStack: 1,
      iconId: "icon.axe",
      worldAssetId: "asset.axe",
      equipmentSlot: "tool",
      toolKind: "hatchet",
      healAmount: 0,
      value: 1,
      collection: false,
      combatBonuses: null,
    },
    log: {
      id: "log",
      name: "Log",
      description: "Test log",
      category: "resource",
      stackable: true,
      maxStack: 100_000,
      iconId: "icon.log",
      worldAssetId: "asset.log",
      equipmentSlot: null,
      toolKind: null,
      healAmount: 0,
      value: 1,
      collection: false,
      combatBonuses: null,
    },
    raw: {
      id: "raw",
      name: "Raw",
      description: "Raw food",
      category: "resource",
      stackable: true,
      maxStack: 100,
      iconId: "icon.raw",
      worldAssetId: "asset.raw",
      equipmentSlot: null,
      toolKind: null,
      healAmount: 0,
      value: 1,
      collection: false,
      combatBonuses: null,
    },
    cooked: {
      id: "cooked",
      name: "Cooked",
      description: "Cooked food",
      category: "food",
      stackable: true,
      maxStack: 100,
      iconId: "icon.cooked",
      worldAssetId: "asset.cooked",
      equipmentSlot: null,
      toolKind: null,
      healAmount: 4,
      value: 2,
      collection: false,
      combatBonuses: null,
    },
    rare: {
      id: "rare",
      name: "Rare",
      description: "Guaranteed test rare",
      category: "rare",
      stackable: true,
      maxStack: 100_000,
      iconId: "icon.rare",
      worldAssetId: "asset.rare",
      equipmentSlot: null,
      toolKind: null,
      healAmount: 0,
      value: 10,
      collection: true,
      combatBonuses: null,
    },
    bone: {
      id: "bone",
      name: "Bone",
      description: "Enemy drop",
      category: "collection",
      stackable: true,
      maxStack: 100,
      iconId: "icon.bone",
      worldAssetId: "asset.bone",
      equipmentSlot: null,
      toolKind: null,
      healAmount: 0,
      value: 2,
      collection: true,
      combatBonuses: null,
    },
    training_blade: {
      id: "training_blade",
      name: "Training Blade",
      description: "Test weapon",
      category: "weapon",
      stackable: false,
      maxStack: 1,
      iconId: "icon.blade",
      worldAssetId: "asset.blade",
      equipmentSlot: "weapon",
      toolKind: null,
      healAmount: 0,
      value: 4,
      collection: false,
      combatBonuses: { accuracy: 12, strength: 5, defence: 0 },
    },
    training_vest: {
      id: "training_vest",
      name: "Training Vest",
      description: "Test armour",
      category: "rare",
      stackable: false,
      maxStack: 1,
      iconId: "icon.vest",
      worldAssetId: "asset.vest",
      equipmentSlot: "body",
      toolKind: null,
      healAmount: 0,
      value: 4,
      collection: false,
      combatBonuses: { accuracy: 0, strength: 0, defence: 20 },
    },
  },
  resources: {
    test_tree: {
      id: "test_tree",
      name: "Test Tree",
      skill: "woodcutting",
      requiredTool: "hatchet",
      actionDurationMs: 10_000,
      successChancePpm: 1_000_000,
      xpPerSuccess: 10,
      masteryXpPerAttempt: 2,
      yield: { itemId: "log", minQuantity: 1, maxQuantity: 1, chancePpm: 1_000_000 },
      rareDrops: [{ itemId: "rare", minQuantity: 1, maxQuantity: 1, chancePpm: 1_000_000 }],
      respawnMs: 0,
      masterySpeedPpmPerRank: 0,
      masteryRarePpmPerRank: 0,
    },
    long_tree: {
      id: "long_tree",
      name: "Long Tree",
      skill: "woodcutting",
      requiredTool: "hatchet",
      actionDurationMs: 21_600_000,
      successChancePpm: 1_000_000,
      xpPerSuccess: 10,
      masteryXpPerAttempt: 2,
      yield: { itemId: "log", minQuantity: 1, maxQuantity: 1, chancePpm: 1_000_000 },
      rareDrops: [],
      respawnMs: 0,
      masterySpeedPpmPerRank: 0,
      masteryRarePpmPerRank: 0,
    },
  },
  recipes: {
    cook_raw: {
      id: "cook_raw",
      name: "Cook Raw",
      skill: "cooking",
      actionDurationMs: 1000,
      xpPerSuccess: 5,
      inputs: [{ itemId: "raw", quantity: 1 }],
      output: { itemId: "cooked", quantity: 1 },
      facilityKind: "cooking_fire",
    },
  },
  enemies: {
    lethal_enemy: {
      id: "lethal_enemy",
      name: "Lethal Enemy",
      combatLevel: 50,
      maxHp: 100,
      attackIntervalMs: 1000,
      accuracy: 10_000,
      evasion: 20,
      armor: 0,
      minDamage: 50,
      maxDamage: 50,
      xpReward: 10,
      loot: [{ itemId: "bone", minQuantity: 1, maxQuantity: 1, chancePpm: 1_000_000 }],
      respawnMs: 1000,
      assetId: "enemy.lethal",
    },
  },
  quests: {
    tutorial: {
      id: "tutorial",
      name: "Tutorial",
      summary: "Test quest",
      steps: [
        {
          id: "pickup_axe",
          kind: "pickup",
          objective: "Pick up axe",
          targetId: "ground_axe",
          itemId: "axe",
          count: 1,
        },
        {
          id: "equip_axe",
          kind: "equip",
          objective: "Equip axe",
          targetId: null,
          itemId: "axe",
          count: 1,
        },
        {
          id: "gather_log",
          kind: "gather",
          objective: "Gather log",
          targetId: null,
          itemId: "log",
          count: 1,
        },
      ],
    },
  },
  zones: {
    meadowrest: {
      id: "meadowrest",
      name: "Meadowrest",
      width: 10,
      depth: 10,
      cellSize: 1,
      spawn: { x: 5, z: 5 },
      terrain: [],
      blockedCells: [],
      scenery: [],
      interactables: [
        {
          id: "ground_axe",
          kind: "ground_item",
          displayName: "Axe",
          assetId: "asset.axe",
          x: 4,
          z: 5,
          resourceId: null,
          itemId: "axe",
          recipeId: null,
          enemyId: null,
          quantity: 1,
          interactionRadius: 0,
          blocks: false,
        },
        {
          id: "tree",
          kind: "resource",
          displayName: "Tree",
          assetId: "asset.tree",
          x: 2,
          z: 2,
          resourceId: "test_tree",
          itemId: null,
          recipeId: null,
          enemyId: null,
          quantity: 0,
          interactionRadius: 1,
          blocks: true,
        },
        {
          id: "long_tree_target",
          kind: "resource",
          displayName: "Long Tree",
          assetId: "asset.tree",
          x: 3,
          z: 2,
          resourceId: "long_tree",
          itemId: null,
          recipeId: null,
          enemyId: null,
          quantity: 0,
          interactionRadius: 1,
          blocks: true,
        },
        {
          id: "fire",
          kind: "facility",
          displayName: "Fire",
          assetId: "asset.fire",
          x: 6,
          z: 5,
          resourceId: null,
          itemId: null,
          recipeId: "cook_raw",
          enemyId: null,
          quantity: 0,
          interactionRadius: 1,
          blocks: true,
        },
        {
          id: "enemy",
          kind: "enemy",
          displayName: "Enemy",
          assetId: "enemy.lethal",
          x: 8,
          z: 8,
          resourceId: null,
          itemId: null,
          recipeId: null,
          enemyId: "lethal_enemy",
          quantity: 0,
          interactionRadius: 1,
          blocks: true,
        },
      ],
    },
  },
};
